### ISSUE TITLE
Dependency Graph

### ISSUE THREAD

**Issue by Ji4n1ng** [kaist-ina/Extractocol#3]
I have run the Program Slicing module for both forward and backward with the arguments provided in your example (wish.apk). After executing the Signature Building module, it shows up in the console that the program extracted 141 URLs. But what baffles me is how I can get the dependency graph between HTTP transactions as you mentioned in your paper.

<img width="383" alt="dg" src="https://user-images.githubusercontent.com/11001224/33651940-7c7583b0-daa2-11e7-9ec7-9422ca82f91c.png">

**Comment by ws1994** [comment]
did you have encountered some errors when you ran it？ I got 0 URL for this test example！

when I run it forward，I got a error

**Comment by jerryhero** [comment]
how to build this project?
